### PR TITLE
Fix issue with usage in TypeScript projects caused by 'compose' re-export

### LINKED ISSUE #279: Cannot find module 'recompose/compose'.
## Steps to Reproduce

Just import `react-apollo`.

### Buggy Behavior

```
[0] /home/zhenghu/coding/qsc/qsc-main-react-typescript/node_modules/react-apollo/index.d.ts
[0] (3,21): error TS2307: Cannot find module 'recompose/compose'.
```

### Expected Behavior

No error.

### Version
- apollo-client@0.4.21
- react-apollo@0.5.11

### PR DESCRIPTION
**Pull request by vlasenko**
Fixes #279 

As suggested by @migueloller `compose` is re-exported from `redux` instead of `recompose`, since implementation is completely the same, that's why we can drop depending on `recompose` completely.

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by migueloller** [comment]
Would it make sense to rebase so that the commit that removes the `recompose` dependency also imports from `redux`? This way the commit makes a non-breaking atomic change and can easily be reverted if necessary.

File: src/index.ts [hunk 1]
```diff
@@ -2,6 +2,6 @@ import ApolloProvider from './ApolloProvider';
 import graphql, { withApollo } from './graphql';
 
 // expose easy way to join queries from recompose
```
Comment (vlasenko) [inline src/index.ts]: Thank you! Done

**Comment by vlasenko** [comment]
Sure. I will try now. I never did this before.... Any pointers appreciated

**Comment by vlasenko** [comment]
Okay, rebased everything into single commit

**Comment by jbaxleyiii** [comment]
@vlasenko this is great, my only concern is with importing all of redux. This probably isn't an issue since apollo-client imports redux. Technically this integration doesn't actually rely on redux at all. 

That being said, I'm great with this for now! Thanks for the PR
